---
all:
  hosts:
  children:
    web_servers:
      hosts:
    db_servers:
      hosts:
    switches:
      hosts:
    production:
      hosts:
    test:
      hosts:
        example_name:
          ansible_host: ip_address 

